# Generated by Django 3.1.3 on 2020-12-05 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_student_studentid'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
